# Generated by Django 5.2.8 on 2025-12-15 13:00

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400, verbose_name='Имя')),
                ('origin_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Имя в оригинале')),
                ('birthday', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
                ('kinopoisk_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kinopoisk ID')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Имя')),
                ('origin_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название (в оригинале)')),
                ('slogan', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Девиз')),
                ('length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность')),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1885)], verbose_name='Год выпуска')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Трейлер')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Постер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('kinopoisk_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kinopoisk ID')),
                ('countries', models.ManyToManyField(related_name='films', to='films.country', verbose_name='страны')),
                ('genres', models.ManyToManyField(related_name='films', to='films.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilmCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.role')),
            ],
            options={
                'verbose_name': 'Участник съемочной группы',
                'verbose_name_plural': 'Съемочная группа',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='people',
            field=models.ManyToManyField(related_name='films', through='films.FilmCrew', to='films.person'),
        ),
    ]
