# Generated by Django 5.2.8 on 2025-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Приоритет'),
        ),
    ]
